### ISSUE TITLE
Since the new wfrp 4th edition your icons for linux broke

### ISSUE THREAD

**Issue by hamofficer** [Forien/foundryvtt-forien-armoury#14]
Since wfrp fixed their linux icons now all of the icons you used aka the various sword icons and such are now broken aka all icons that use the wfrp 4th system ones

systems/wfrp4e/icons/equipment/weapons/Sword-HW.png
but should be
systems/wfrp4e/icons/equipment/weapons/sword-hw.png
Arming sword
Side-Sword
Sabre
Longsword
Katzbalger
Falchion
Cutlass
Basket-hilt Sword
Backsword

systems/wfrp4e/icons/equipment/weapons/Spear.png
but should be
systems/wfrp4e/icons/equipment/weapons/spear.png
Bear Spear

systems/wfrp4e/icons/equipment/weapons/bludgeon-HW.png
but should be
systems/wfrp4e/icons/equipment/weapons/bludgeon-hw.png
Club

systems/wfrp4e/icons/equipment/weapons/Dagger.png
but should be
systems/wfrp4e/icons/equipment/weapons/dagger.png
Dirk

systems/wfrp4e/icons/equipment/weapons/Foil.png
but should be
systems/wfrp4e/icons/equipment/weapons/foil.png
Estoc

systems/wfrp4e/icons/equipment/weapons/handaxe-HW.png
but should be
systems/wfrp4e/icons/equipment/weapons/handaxe-hw.png
Hatchet

systems/wfrp4e/icons/equipment/weapons/Pick.png
but should be
systems/wfrp4e/icons/equipment/weapons/pick.png
Horseman's Pick

systems/wfrp4e/icons/equipment/weapons/Warhammer-fine.png
but should be 
systems/wfrp4e/icons/equipment/weapons/warhammer-fine.png
Lucerne

systems/wfrp4e/icons/equipment/weapons/Halberd.png
but should be
systems/wfrp4e/icons/equipment/weapons/halberd.png
Pollaxe

systems/wfrp4e/icons/equipment/weapons/Dagger-fine.png
but should be
systems/wfrp4e/icons/equipment/weapons/dagger-fine.png
Stiletto
Misericorde

**Comment by Forien** [comment]
And same probably happened to everyone who imported items with broken images from Compendiums (mine or WFRP4E's) to the world. Because no backward compatibility :P 

Thanks for reporting, will update soon

**Comment by Forien** [comment]
Fixed in v0.2.7. Closing.
