### ISSUE TITLE
[BUG] Missing images

### ISSUE THREAD

**Issue by DrDoomDEU** [Forien/foundryvtt-forien-armoury#22]
**Problem:**
It seems like quite an amount if images is missing.

**What i did:**
Standard installation from inside Foundry VTT.

**Comment by Forien** [comment]
Module was made for WFRP4e version 1.6.2 and depends on images set by system. Because of main system updating number of images broke. I'm looking for replacement, but it's not easy to find nice images that I could redistribute.

**Comment by illotum** [comment]
v1.6.2 is still available -- and the images are missing even when I'm on it. Looks like paths rely on a module (not system) `wfrp4e-content`

**Comment by DrunXX** [comment]
It's not working with current c7 wfrp4 mode?

**Comment by BielinskiLukasz** [comment]
You should find pask/armoury.db file and change all 'wfrp4e-content' occurs to 'wfrp4e-core' :)
